# @see
#   http://docs.travis-ci.com/user/build-configuration/
#   http://docs.travis-ci.com/user/ci-environment/
#
# To skip some tests:
#   @unittest.skip("Unconditional skipping")
#   @unittest.skipIf(os.getenv('CONTINUOUS_INTEGRATION', '') > '', reason='Travis VM')

# http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false
language: python
cache: pip
python:
    - "2.7"

branches:
    only:
        - master
        - develop

# __1 Use this to prepare the system to install prerequisites or dependencies
before_install:
    - echo "Nothing to do"

# __2 Use this to install any prerequisites or dependencies necessary to run your build
install:
    - pwd
    - pip install fabric coveralls pytz
    - pushd app
    - fab prep_develop
    - popd

# __3 Use this to prepare your build for testing
before_script:
    - echo "Creating the database..."
    - mysql -uroot < app/db/000/upgrade.sql
    - echo "Creating the tables..."
    - mysql -uroot ctsi_dropper_s < app/db/001/upgrade.sql
    - mysql -uroot ctsi_dropper_s < app/db/002/upgrade.sql
    - echo "Adding data..."
    - mysql -uctsi_dropper_s -pinsecurepassword ctsi_dropper_s < app/db/002/data.sql

# __4 All commands must exit with code 0 on success. Anything else is considered failure.
script:
    - pushd app
    - echo $TRAVIS_BUILD_DIR
    - ls -al deploy/
    # link the settings file to make it visible in config.py
    - ln -sfv deploy/sample.vagrant.settings.conf deploy/settings.conf
    - python setup.py nosetests
    - popd

# __5a after_success
after_success:
    - pushd app
    - coveralls -v
    - popd

# __5b
after_failure:
    echo "Broken."

# __6
after_script:
    echo "Cleanup."
