# @see
#   http://docs.travis-ci.com/user/build-configuration/
#   http://docs.travis-ci.com/user/ci-environment/
#
# To skip some tests:
#   @unittest.skip("Unconditional skipping")
#   @unittest.skipIf(os.getenv('CONTINUOUS_INTEGRATION', '') > '', reason='Travis VM')

# The redidropper/startup/initializer.py does not need the env variable anymore
#env: REDIDROPPER_CONFIG=~/build/ctsit/redi-dropper-client/app/deploy/application.conf

language: python
python:
    - "2.7"

branches:
    only:
        - master
        - develop

# __1 Use this to prepare the system to install prerequisites or dependencies
before_install:
    - sudo apt-get install -y python-setuptools python-dev

# __2 Use this to install any prerequisites or dependencies necessary to run your build
install:
    - pwd
    - pip install fabric coveralls pytz
    - pushd app
    - fab prep_develop
    - popd

# __3 Use this to prepare your build for testing
before_script:
    - echo "Creating the database..."
    - mysql -uroot < app/db/000/upgrade.sql
    - echo "Creating the tables..."
    - mysql -uroot ctsi_dropper_s < app/db/001/upgrade.sql
    - mysql -uroot ctsi_dropper_s < app/db/002/upgrade.sql
    - echo "Adding data..."
    - mysql -uctsi_dropper_s -pinsecurepassword ctsi_dropper_s < app/db/002/data.sql

# __4 All commands must exit with code 0 on success. Anything else is considered failure.
script:
    - pushd app
    - echo $TRAVIS_BUILD_DIR
    - ls -al deploy/
    # put config file in the place expected by config.py
    - cp deploy/sample.settings.conf deploy/settings.conf
    - fab coverage
    - popd

# __5a after_success
after_success:
    - coveralls --output=coverage.json
    - coveralls -v

# __5b
after_failure:
    echo "Broken."

# __6
after_script:
    echo "Cleanup."
