# From http://docs.travis-ci.com/user/build-configuration/

language: python
python:
    - "2.7"

branches:
    only:
        - master
        - develop

# __1 Use this to prepare the system to install prerequisites or dependencies
before_install:
    sudo apt-get install -y python-setuptools python-dev

# __2 Use this to install any prerequisites or dependencies necessary to run your build
install:
    - pip install Flask
    - pip install Flask-SQLAlchemy
    - pip install fabric

# __3 Use this to prepare your build for testing
before_script:

# __4 All commands must exit with code 0 on success. Anything else is considered failure.
script:
    fab test

# __5a after_success
after_success:
    echo "OK."

# __5b
after_failure:
    echo "Broken."

# __6
after_script:
    echo "Cleanup."
