# From http://docs.travis-ci.com/user/build-configuration/

notifications:
  email:
    - indera@gmail.com



language: python
python:
    - "2.7"

branches:
    only:
        - master
        - develop

# __1 Use this to prepare the system to install prerequisites or dependencies
before_install:
    sudo apt-get install -y python-setuptools python-dev

# __2 Use this to install any prerequisites or dependencies necessary to run your build
install:
    - pwd
    - pip install fabric coveralls
    - ls -al
    - pushd app
    - fab install_requirements
    - popd

# __3 Use this to prepare your build for testing
before_script:
    - echo "Creating the database and tables..."
    - mysql -uroot < app/db/001/upgrade.sql
    - mysql -uroot < app/db/002/upgrade.sql
    - mysql -uredidropper -pinsecurepassword < app/db/002/data.sql
    - cp app/redidropper/startup/application.cfg.example app/redidropper/startup/application.cfg
    - export REDIDROPPER_CONFIG=~/build/ctsit/redi-dropper-client/app/redidropper/startup/application.cfg

# __4 All commands must exit with code 0 on success. Anything else is considered failure.
script:
    - pushd app
    - fab test_cov
    - popd

# __5a after_success
after_success:
    - coveralls

# __5b
after_failure:
    echo "Broken."

# __6
after_script:
    echo "Cleanup."
